# ====================================
# Fluent-Bit 서비스의 전역 행동 설정
# 수집 -> 전처리/추출 x -> 적제(배달) 컨셉
# logstash 연계가(약간의 지연발생) 없었다면 여기서 전처리/필터링등등 작업이 수행될수 있음
# ====================================
[SERVICE]
    Flush           1
    Log_Level       info
    Parsers_File    /fluent-bit/etc/parsers.conf
    storage.path    /fluent-bit/storage
    storage.sync    normal
    storage.backlog.mem_limit 5M
    storage.total_limit_size 512M

# ====================================
# 데이터 수집 Input -> 어디서 데이터를 가져올 것인가
# Input : sensor_json.log
# ====================================
[INPUT]
    # 파일에 끝(tail)에서 읽어온다 -> 플러그인
    Name    tail
    # 읽어올 로그 파일 경로 -> 날짜가 바뀌면, 파일이 커지면? 해결
    Path    /data/sensor_logs/sensor_json.log
    # 해당 데이터에 tag 표시, 차후 [Output]에서 태그를 보고 어디로 전송할지 필터링함
    Tag     sensor.json
    # 파일 내용을 미리 정의된 json 파서를 활용하여 구조화된 데이터로 인식 -> 후속 작업은 없음
    Parser  sensor_json
    DB                /fluent-bit/state/sensor_json.db
    DB.Sync           Normal
    Read_from_Head    true
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On
    storage.type      filesystem

# ====================================
# Input : sensor_text.log
# ====================================
[INPUT]
    Name    tail
    Path    /data/sensor_logs/sensor_text.log
    Tag     sensor.text
    DB                /fluent-bit/state/sensor_text.db
    DB.Sync           Normal
    Read_from_Head    true
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On
    storage.type      filesystem

# ====================================
# 데이터 배포 Output -> 데이터를 어디로 보낼 것인가
# Output : k
# ====================================
[OUTPUT]
    # kafka 출력 플러그인 사용
    Name    kafka
    # tag가 sensor.json 인 데이터만 출력 설정 => 필터링
    Match   sensor.json
    # 전송할곳 엔드포인트 (kafka의 브로커의 주소)
    # (도커컴포즈 구성시 서비스명):포트 => AWS MSK의 엔드포인트로 교체
    Brokers kafka:9092
    # 데이터를 카프카로 보낼때 -> 토픽명
    Topics  factory.sensor.raw.json.v1
    # 전송되는 데이터의 형식 -> JSON 형태 유지
    Format  json
    rdkafka.message.send.max.retries 10
    Retry_Limit 10

# ====================================
# Output : logstash (http 전송)
# ====================================
[OUTPUT]
    # Fluent-Bit로 logstash간 http 전송
    Name    http
    # tag가 sensor.text 인 데이터만 출력
    Match   sensor.text
    # logstash의 엔드포인트
    Host    logstash
    Port    5044
    URI     /
    Format  json
    Retry_Limit 10
