# =====================================
# Fleunt-Bit 서비스의 전역 행동 설정
# 수집 -> 전처리/추출 x -> 적제(배달) 컨셉
# logstash 연계(약간의 지연발생 + java 기반이라 무거움)가 없었다면 여기서 전처리/필터등등 작업이 수행 가능
# =====================================
[SERVICE]
    Flush       1       # 수집된 데이터를 몇 초 간격으로 내보낼(출력)것인가 설정, 1초마다 데이터 전송 -> 실시간성
    Log_Level   info    # Fluent-Bit 로그에 대한 레벨 설정. (error,war,info,debug), info: 일반 실행 정보, debug까지 출력 -> 자기 설정한 레벨의 밑 레벨애들까지 출력
# =====================================
# 데이터 수집 Input -> 어디서 데이터를 가져 올 것인가
# Input : sensor_json.log
# =====================================
[INPUT]
    Name    tail                                     # 파일에 끝(tail)에서 읽어온다 -> 플러그인
    Path    /opt/airflow/sensor_logs/sensor_json.log # 읽어올 로그 파일 경로 -> 날짜가 바뀌면, 파일이 커지면? 해결
    Tag     sensor.son                               # 해당 데이터에 tag 표시, 차후 [Output]에서 태그를 보고 어디로 전송할지 결정
    Parser  json                                     # 파일 내용을 미리 정의된 json 파서를 활용해서 구조화된 데이터로 인식 -> 후속 작업 x
# =====================================
# Input : sensor_text.log
# =====================================
[INPUT]
# =====================================
# 데이터 배포 Output -> 데이터를 어디로 보낼 것인가
# Output : kafka
# =====================================
[OUTPUT]
# =====================================
# Output : logstash
# =====================================
[OUTPUT]
