input {
    http {
        port => 5044
        codec => json
    }
}

filter {
    if [log] {
        grok {
            ecs_compatibility => "disabled"
            match => {
                "log" => "\[%{TIMESTAMP_ISO8601:event_time}\]\s+ID=%{DATA:sensor_id}\s+\|\s*TEMP:%{NUMBER:temperature:float}\s+\|\s*HUMI:%{NUMBER:humidity:float}\s+\|\s*STAT:%{WORD:status}"
            }
            tag_on_failure => ["_sensor_contract_parse_failure"]
        }
        mutate {
            rename => {
                "device_id" => "sensor_id"
                "temp" => "temperature"
                "humi" => "humidity"
                "log_time" => "event_time"
            }
            convert => {
                "temperature" => "float"
                "humidity" => "float"
            }
        }
    }
}

output {
    kafka {
        bootstrap_servers => "kafka:9092"
        topic_id => "factory.sensor.raw.text.v1"
        codec => json
        acks => "all"
    }
    # 확인용 콘솔 출력 로그
    stdout {
        codec => rubydebug
    }
}
